---
- hosts: all
  roles: 
    - common

- ansible.builtin.import_playbook: interface_setup.yml
- ansible.builtin.import_playbook: encryption_setup.yml
- ansible.builtin.import_playbook: routing_setup.yml
